### PR TITLE
Fix: broaden TextMate scopes for syntax coloring

### LINKED ISSUE #1: feat: improved semantic coloring
### Summary
Syntax coloring appears missing across Caligo themes (keywords/strings/functions not visually distinct).

### Expected
Syntax tokens should be colored per token scope rules in Caligo theme JSON.

### Actual
Syntax coloring is minimal or absent in editor views.

### Notes
Token scopes were too narrow for many grammars. Expanding TextMate scopes should restore visible syntax coloring.

### Proposed Fix
Expand TextMate token scopes (keywords/functions/types/variables/constants/operators/tags/attributes) in generator.

### PR DESCRIPTION
**Pull request by Anselmoo**
## Summary
Restore visible syntax coloring by broadening TextMate scope coverage across keywords, functions, types, variables, constants, operators, tags, and attributes.

Closes #1

## Changes
- Expand TextMate scope lists for core syntax roles
- Add tag and attribute token color entries for HTML/JSX/TSX and similar grammars
- Keep generation artifacts out of the repo per policy

## How to test
1. Run `npm run generate` (optional if you only want source changes)
2. In VS Code, open a file and use “Developer: Inspect Editor Tokens and Scopes” to confirm scopes match the updated lists
3. Switch to any Caligo theme and verify strings/keywords/functions render with distinct colors

## Notes
- Hooks ran on push (build + tests + underscore check).

### CODE REVIEW

File: src/lib/vscode-theme.ts [hunk 1]
```diff
@@ -216,39 +391,112 @@ export function buildVscodeThemeJson(p: DerivedPalette): VscodeThemeJson {
...
+        "keyword.operator",
+        "punctuation.separator",
+        "punctuation.accessor",
+        "punctuation.terminator",
+        "punctuation.section",
+        "punctuation.definition.template-expression",
+      ],
       settings: { foreground: withAlpha(p.fg0, 0.85) },
     },
+    {
```
Comment (Anselmoo) [inline src/lib/vscode-theme.ts]: Nice — adding explicit tag scopes should restore markup syntax coloring across HTML/JSX/TSX.
